# Generated by Django 5.2.7 on 2025-10-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Developers_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voice', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publishers_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_game', models.CharField(max_length=200, unique=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_web.developer')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_web.genre')),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_web.localization')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_web.publisher')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_web.tags')),
            ],
        ),
    ]
